  env:
    node: true
    es6: true
  
  plugins:
    - babel
  
  parser: babel-eslint
  parserOptions:
    ecmaVersion: 6
    sourceType: module
    allowImportExportEverywhere: true
    experimentalObjectRestSpread: true
    codeFrame: true
   
  rules:
    no-console: 0
    "import/no-named-as-default": 0,
    "import/no-named-as-default-member": 0
    
  extends:
    - 'airbnb-base'
