  env:
    node: true
  
  plugins:
    - babel
  
  parser: babel-eslint
  parserOptions:
    sourceType: module
    allowImportExportEverywhere: true
  
  rules:
    no-console: 0
    
  extends:
    - 'airbnb-base'
